# Generated by Django 4.1.2 on 2022-10-29 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('bio', models.TextField(blank=True, null=True)),
                ('avatar', models.ImageField(default='blank-profile-avatar.png', upload_to='profile/avatars')),
                ('background_profile_photo', models.ImageField(default='blank-profile-background.png', upload_to='profile/backgrounds')),
                ('gender', models.IntegerField(default=None, null=True)),
                ('date_of_birth', models.DateField(auto_now=True)),
                ('website', models.CharField(blank=True, max_length=255, null=True)),
                ('country_id', models.IntegerField(default=None, null=True)),
                ('city_id', models.IntegerField(default=None, null=True)),
                ('citizenship', models.CharField(blank=True, max_length=255, null=True)),
                ('tin', models.IntegerField(default=None, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('university', models.CharField(blank=True, max_length=255, null=True)),
                ('speciality', models.CharField(blank=True, max_length=255, null=True)),
                ('ending_year', models.DateField(auto_now=True)),
                ('employment_id', models.IntegerField(default=None, null=True)),
                ('skills', models.TextField(blank=True, null=True)),
                ('work_experience', models.IntegerField(default=None, null=True)),
                ('achievements', models.TextField(blank=True, null=True)),
                ('hackathons', models.IntegerField(default=None, null=True)),
                ('role', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('has_team', models.BooleanField(default=False)),
                ('has_project', models.BooleanField(default=False)),
                ('has_company', models.BooleanField(default=False)),
                ('has_patent', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
