# Generated by Django 4.1.2 on 2022-10-29 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='background_profile_photo',
            field=models.ImageField(default='blank-profile-background.jpg', upload_to='profile/backgrounds'),
        ),
    ]
