# Generated by Django 4.1.2 on 2022-11-01 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(default='blank-profile-background.jpg', upload_to='project'),
        ),
    ]
