# Generated by Django 4.1.2 on 2022-10-29 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='city_id',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='country_id',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='employment_id',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='hackathons',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='tin',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='work_experience',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
