# Generated by Django 4.1.2 on 2022-11-01 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_project_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(default='blank-project-image.jpg', upload_to='project'),
        ),
    ]
